##
title: stjep.co
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Stjepan Grgic.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stjep.co" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

#Where things are
source:         ./src
destination:    ./dist

#relative to source folder - wtf?
layouts_dir:    ./_layouts
includes_dir:   ./_includes

keep_files: ["assets"]
include: ["_pages"]

# TODO
# gems:
#   - jekyll-feed

exclude: ["gulpfile.js", "Gemfile", "Gemfile.lock", "package.json", "README.md", "LICENSE", "node_modules"]

collections:
  experiments:
    output: true
    permalink: /lab/:path/

defaults:
  -
    scope:
      path: ""
      type: "experiments" # a collection in your site, in plural form
    values:
      layout: "experiment"
      status: "done"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"