# Site settings
title: stjepco
email: grgic.stjepan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome stjepco's web site 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stjep.co" # the base hostname & protocol for your site
twitter_username: stjepco
github_username:  stjepco

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap