# stjep.co settings
title:              stjepco
email:              grgic.stjepan@gmail.com

baseurl:            ""
url:                "http://stjep.co"

permalink:           "/blog/:title/"

# paginate:            5
# paginate_path:       "/blog/page:num/"

include:             ["_pages"]
# relative_permalinks: false




collections:
  works:
    output: true
    permalink: /work/:title/