# Site settings
title: stjepco
email: grgic.stjepan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome stjepco's web site 
baseurl: ""
url: "http://stjep.co"
twitter_username: stjepco
github_username:  stjepco

# Build settings
markdown: kramdown

