# stjep.co settings
title: stjep.co

baseurl: ""
url: "http://stjep.co"

# Build settings
markdown: kramdown

include: ["_pages"]

exclude: ["gulpfile.js", "Gemfile", "Gemfile.lock",
          "package.json", "README.md", "LICENSE", "node_modules"]

