# Site settings
title: stjepco
email: grgic.stjepan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome stjepco's web site 
baseurl: ""
url: "http://stjep.co"
twitter_username: stjepco
github_username:  stjepco

# Build settings
markdown: kramdown

# gems:
#   - jekyll-sitemap

# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#       author: Stjepan Grgic
#     values:
#       layout: "posts"
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "page"